# Generated by Django 5.0.7 on 2024-07-17 17:22

from django.db import migrations
import pandas as pd
import os

def load_csv_data(apps, data):
    products = apps.get_model('base', 'Product')
    try:
        csv_path = 'Products.csv'
        df = pd.read_csv(csv_path)
        df['InStock'].fillna(0, inplace=True)
        df['Ratings'].fillna(0, inplace=True)
        df['Reviews'].fillna(0, inplace=True)
        for _,row in df.iterrows():
            products.objects.create(
                name = row['ProductName'],
                image = os.path.relpath(row['Image'],'/images'),
                brand = row['Brand'],
                category = row['Category'],
                description = row['Description'],
                rating = row['Ratings'],
                numReviews = row['Reviews'],
                price = row['Price'],
                countInStock = row['InStock']
            )
    except Exception as e:
        print(e.message, e.args)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_image'),
    ]

    operations = [
        migrations.RunPython(load_csv_data)
    ]
